/home/pi/.pm2/logs/*.log /home/pi/.local/state/teliman-backup/*.log {
    daily
    rotate 14
    maxsize 20M
    missingok
    notifempty
    compress
    delaycompress
    copytruncate
    create 0600 pi pi
}
